spring:
  datasource:
    url: jdbc:mysql://localhost/rp_mall?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 1
    maxActive: 20
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
logging:
   level:
     com:
       company:
           project: debug